# Generated by Django 4.2.13 on 2024-07-10 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presence.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_approved', models.CharField(choices=[('en cour de traitement', 'en cour de traitement'), ('approuvé', 'approuvé'), ('refusé', 'refusé')], default='en cour de traitement', max_length=25)),
                ('date_send', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('en cour de traitement', 'en cour de traitement'), ('approuvé', 'approuvé'), ('refusé', 'refusé')], default='', max_length=100)),
                ('employee', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='presence.employee')),
            ],
            options={
                'unique_together': {('employee', 'start_date', 'end_date')},
            },
        ),
    ]
