# Generated by Django 4.2.16 on 2025-02-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_employee_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
